FROM ubuntu:14.04
MAINTAINER svanoort <samvanoort@gmail.com>

RUN apt-get update && apt-get install --no-install-recommends -y python python-dev python-pip python-pycurl git-core \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && pip install mock pyyaml django==1.6.5 django-tastypie

COPY verify_image.py /tmp/verify_image.py